### ISSUE TITLE
Color not changing with HIC single data type

### ISSUE THREAD

**Issue by rnr-HMS** [alosdiallo/HiC_Network_Viz_tool#26]
Color not changing with HIC single data type
![Screen Shot 2019-04-10 at 2 17 55 PM](https://user-images.githubusercontent.com/30178718/55904903-e5361d00-5b9e-11e9-8912-546bb0e4a07a.png)

**Comment by KHBHH** [comment]
I think this is fixed now, but please double check.

**Comment by rnr-HMS** [comment]
Hi Karni,
Still have this issue. Using the single data set.
<img width="1440" alt="Screen Shot 2019-04-11 at 7 28 30 PM" src="https://user-images.githubusercontent.com/30178718/56002347-088cc500-5c90-11e9-8538-5525adfe1aad.png">

**Comment by rnr-HMS** [comment]
Also looks like bezier coloring is an issue with multiple samples. Look at this example. There are red links in the network but not in the bezier plot
<img width="1440" alt="Screen Shot 2019-04-11 at 7 58 54 PM" src="https://user-images.githubusercontent.com/30178718/56003380-57d4f480-5c94-11e9-8c51-4e5621f12494.png">

**Comment by KHBHH** [comment]
With single HIC , it is fixed now. You can check it to confirm.

But please can you check if multiple HiC samples work too?

**Comment by alosdiallo** [comment]
Closing as i think this is fixed
